import java.util.concurrent.ExecutionException;

public class Test {

	public static void main(String[] args) throws Exception{
		Enfant e =new Enfant(9);
		Enfant e2 =new Enfant();
		e2.setAge(22);
		
		
		
				
		
		

	}
 
}
